version: '3'

services:
  pricer-api:
    container_name: pricer-api
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    build:
      context: pricer-api
      dockerfile: Dockerfile
    image: pricer-api:latest
    ports:
      - "8080:8080"
  pricer_db:
    image: postgres
    container_name: "pricer_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  pricer_pgadmin4:
    container_name: "pricer_pgadmin4"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data:
